main: me.rejomy.money.Main
version: 1.0
name: KillMoney
api-version: 1.13

command:
  killmoney:
    permission: killmoney.command
    permission-message: You dont have permission killmoney.command to execute this command.

softdepend:
  - vault